title:  
owner: onurhan irkin
email: onurhan.irkin@gmail.com
description: 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://onurhani.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: onur_irkin
github_username: onurhani
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
